# Example workflow using the jira-release action
name: Generate Jira Release

on:
  workflow_dispatch:
    inputs:
      release-name:
        description: 'Name of release (default to current yyyy-mm-dd if no release already exists)'
        required: false
        default: ''

env:
  # kosli commands picks up org, flow, trail and api-token from these environment variables
  KOSLI_ORG: "${{ vars.KOSLI_ORG }}"
  KOSLI_FLOW: "jira-multi-repo-release"
  KOSLI_ENV_PROD: "jira-multi-repo-prod"
  KOSLI_API_TOKEN: "${{ secrets.KOSLI_PUBLIC_API_TOKEN }}"
  KOSLI_CLI_VERSION: "${{ vars.KOSLI_CLI_VERSION }}"
  KOSLI_TEMPLATE_FILE: "kosli-flow-templates/release-template.yml"
  JIRA_BASE_URL: "${{ vars.KOSLI_JIRA_BASE_URL }}"
  JIRA_USERNAME: ${{ vars.KOSLI_JIRA_USERNAME }}
  JIRA_API_TOKEN: ${{ secrets.KOSLI_JIRA_API_TOKEN }}
  JIRA_PROJECT_KEY: ${{ vars.JIRA_PROJECT_KEY }}
  JIRA_PROJECT_ID: ${{ vars.JIRA_PROJECT_ID }}

jobs:
  generate-jira-release:
    name: Create or update Jira release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Kosli cli
        uses: kosli-dev/setup-cli-action@v2
        with:
          version:
            ${{ vars.KOSLI_CLI_VERSION }}

      - name: Create or get Jira release candidate
        id: release-candidate
        run: |
          echo "STEP: Create or get Jira release candidate"
          source .github/actions/common/lib-jira.sh
          
          CURRENT_REL_JSON=$(get_current_release_candidate ${JIRA_PROJECT_ID})
          REL_VALUES_JSON=$(echo "${CURRENT_REL_JSON}" | jq .values)
          if [ "${REL_VALUES_JSON}" == "[]" ]; then
            echo "No release candidate exist"
            echo "release-was-created=true" >> $GITHUB_OUTPUT
          
            # Create the release and get the release ID
          
            RELEASE_NAME="${{ github.event.inputs.release-name }}"
            if [ -z "$RELEASE_NAME" ]; then
              RELEASE_NAME=$(date -u "+%Y-%m-%d")
            fi
            CREATE_RESULT_JSON=$(create_release ${JIRA_PROJECT_ID} ${RELEASE_NAME})
            RELEASE_ID=$(echo "${CREATE_RESULT_JSON}" | jq -r '.id')
          
            PROJECT_KEY=$(echo "${JIRA_PROJECT_ID}" | cut -d',' -f1)
            REL_LINK="${JIRA_BASE_URL}/projects/${PROJECT_KEY}/versions/${RELEASE_ID}"
            echo "REL_LINK=${REL_LINK}" >> $GITHUB_ENV
            echo "Created Jira release_name: **${RELEASE_NAME}**" >> $GITHUB_STEP_SUMMARY
            echo "release_id: **${RELEASE_ID}**" >> $GITHUB_STEP_SUMMARY
          else
            echo "Release candidate exist"
            RELEASE_ID=$(echo "${REL_VALUES_JSON}" |  jq -r '.[0].id')
            RELEASE_NAME=$(echo "${REL_VALUES_JSON}" |  jq -r '.[0].name')
            echo "Updated Jira release_name: **${RELEASE_NAME}**" >> $GITHUB_STEP_SUMMARY
            echo "release_id: **${RELEASE_ID}**" >> $GITHUB_STEP_SUMMARY
          fi
          echo "RELEASE_ID=${RELEASE_ID}" >> $GITHUB_ENV
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV

      - name: Begin trail
        if: ${{ steps.release-candidate.outputs.release-was-created == 'true' }}
        shell: bash
        run: |
          echo "STEP: Begin trail with ORG: '${KOSLI_ORG}' FLOW: '${KOSLI_FLOW}' TRAIL: '${{ env.RELEASE_NAME }}' TEMPLATE-FILE: '${KOSLI_TEMPLATE_FILE}'"
          kosli begin trail ${{ env.RELEASE_NAME }} --template-file ${KOSLI_TEMPLATE_FILE} --external-url JiraRelease=${{ env.REL_LINK }}


      - name: Add trail to jira release
        if: ${{ steps.release-candidate.outputs.release-was-created == 'true' }}
        shell: bash
        run: |
          echo "STEP: Add trail to jira release"
          source .github/actions/common/lib-jira.sh
          kosli_trail_link="https://app.kosli.com/${KOSLI_ORG}/flows/${KOSLI_FLOW}/trails/${{ env.RELEASE_NAME }}"
          add_trail_link_to_release ${{ env.RELEASE_ID }} ${kosli_trail_link}

      - name: Report current prod SW
        if: ${{ steps.release-candidate.outputs.release-was-created == 'true' }}
        shell: bash
        run: |
          echo "STEP: Report current prod SW"
          source .github/actions/common/lib-kosli.sh
          get_current_running_env_json ${KOSLI_ENV_PROD} > /tmp/prod-env.json
          create_running_sw_short_list_json /tmp/prod-env.json > /tmp/prod-sw.json
          
          kosli attest custom \
            --type=running-sw \
            --name prod-software \
            --trail ${{ env.RELEASE_NAME }} \
            --attestation-data /tmp/prod-sw.json
          echo "Current prod SW:" >> $GITHUB_STEP_SUMMARY
          cat /tmp/prod-sw.json | jq >> $GITHUB_STEP_SUMMARY

      - name: Collect jira issues and software update plan
        shell: bash
        run: |
          echo "STEP: Collect jira issues and software update plan"
          source .github/actions/common/lib-kosli.sh
          [ -f /tmp/prod-env.json ] || get_current_running_env_json "${KOSLI_ENV_PROD}" > /tmp/prod-env.json
          get_list_of_artifacts_with_release_flow_info /tmp/prod-env.json >  /tmp/prod-release-sw-versions.json
          
          echo AAAA
          cat /tmp/prod-env.json
          echo BBBB
          cat  /tmp/prod-release-sw-versions.json
          echo CCCC
      
          # Loop over all artifacts, find the all the trails that are newer then what is running now
          ALL_ISSUES_FILE="/tmp/all_issues.txt"
          > ${ALL_ISSUES_FILE}
          SW_UPDATE_PLAN_FILE="/tmp/sw-update-plan.txt"
          > ${SW_UPDATE_PLAN_FILE}
      
          # Create JSON objects for each artifact instead of simple key=value
          while read -r artifact_env_name flow_name trail_name artifact_name; do
            # Use artifact_env_name if artifact_name is empty
            if [[ -z "$artifact_name" ]]; then
              artifact_name="$artifact_env_name"
            fi

            get_trails_newer_then ${flow_name} ${trail_name} > /tmp/${artifact_name}.json
      
            NEXT_VERSION=$(jq -r '.[0].name' /tmp/${artifact_name}.json)
            if [ "$NEXT_VERSION" == "null" ]; then
              NEXT_VERSION="$trail_name"
            fi
      
            # Create JSON object with both current and next versions
            jq -n \
              --arg artifact "$artifact_name" \
              --arg current "$trail_name" \
              --arg next "$NEXT_VERSION" \
              --arg flow "$flow_name" \
              '{($artifact): {"current-sw": $current, "next-sw": $next, "release-flow": $flow}}' >> ${SW_UPDATE_PLAN_FILE}
      
             # Loop over the trails to get a list of Jira issues
             for trail in $(jq -r '.[].name' /tmp/${artifact_name}.json); do
               get_attestation_from_trail ${flow_name} ${trail} "jira-issues" | jq -r '.[].attestation_data[]?' >> ${ALL_ISSUES_FILE}
             done
          done < <(jq -r '.[] | "\(.name) \(.flow_name) \(.trail_name) \(.template_reference_name)"' /tmp/prod-release-sw-versions.json)
      
          ISSUES=$(sort -uV "${ALL_ISSUES_FILE}" | tr '\n' ' ' | sed 's/ *$//')
          echo ${ISSUES} | jq -R 'split(" ")' > /tmp/jira-issues.json
          echo "JIRA_KEYS_IN_KOSLI_RELEASES=${ISSUES}" >> $GITHUB_ENV
      
          jq -s 'add' ${SW_UPDATE_PLAN_FILE} > /tmp/sw-update-plan.json

      - name: Attest jira issues to kosli trail
        shell: bash
        run: |
          echo "STEP: Attest jira issues"
          
          ISSUES="${{ env.JIRA_KEYS_IN_KOSLI_RELEASES }}"
          
          kosli attest custom \
            --type=jira-issues-list \
            --name jira-issues \
            --trail ${{ env.RELEASE_NAME }} \
            --attestation-data /tmp/jira-issues.json \
            --annotate "JiraIssues=${ISSUES}"
          
          echo "Attested Jira issues to kosli release ${{ env.RELEASE_NAME }}: **${ISSUES}**" >> $GITHUB_STEP_SUMMARY

      - name: Attest software update plan to kosli trail
        shell: bash
        run: |
          echo "STEP: Attest software update plan"
          
          kosli attest custom \
            --type=sw-update-plan \
            --name sw-update-plan \
            --trail ${{ env.RELEASE_NAME }} \
            --attestation-data /tmp/sw-update-plan.json
          
          echo "Attested Next SW kosli release ${{ env.RELEASE_NAME }}:" >> $GITHUB_STEP_SUMMARY
          cat /tmp/sw-update-plan.json >> $GITHUB_STEP_SUMMARY      

      - name: Add Jira issues to release
        shell: bash
        run: |
          echo "STEP: Add Jira issues to release"
          source .github/actions/common/lib-jira.sh
          source .github/actions/common/lib-kosli.sh

          JIRA_KEYS_IN_REL=($(get_issue_keys_in_release ${{ env.RELEASE_ID }}))
          JIRA_KEYS_IN_KOSLI=(${{ env.JIRA_KEYS_IN_KOSLI_RELEASES }})

          # Add all new jira issues between prod and staging
          echo "Added Jira issues to Jira release ${{ env.RELEASE_NAME }}:"  >> $GITHUB_STEP_SUMMARY
          for JIRA_KEY in ${JIRA_KEYS_IN_KOSLI[@]}; do
            if [[ ! " ${JIRA_KEYS_IN_REL[@]} " =~ " ${JIRA_KEY} " ]]; then
              add_issue_to_release ${JIRA_KEY} ${{ env.RELEASE_ID }}
              echo ${JIRA_KEY} >> $GITHUB_STEP_SUMMARY
            fi
          done
